[phases.setup]
nixPkgs = ['php82', 'php82Extensions.mongodb']

[phases.install]
cmds = ['composer install --optimize-autoloader']

[phases.build]
cmds = [
  'mkdir -p bootstrap/cache',
  'chmod -R 777 bootstrap/cache',
  'mkdir -p storage/framework/{sessions,views,cache}',
  'chmod -R 777 storage',
  'php artisan package:discover'
]

[start]
cmd = "mkdir -p bootstrap/cache && chmod -R 777 bootstrap/cache && mkdir -p storage/framework/{sessions,views,cache} storage/logs && chmod -R 777 storage && php artisan config:clear && php artisan cache:clear && php artisan route:clear && php artisan serve --host=0.0.0.0 --port=$PORT"