name: Tests

on:
  push:
    branches:
      - master
      - "*.x"
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3, 8.4]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mongodb
          coverage: none

      - name: Install Composer dependencies
        run: |
          if [ "${{ matrix.php }}" == "8.2" ]; then
            composer install --prefer-dist --no-interaction --no-progress
          else
            composer install --prefer-dist --no-interaction --no-progress --ignore-platform-req=ext-mongodb
          fi

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Execute tests
        run: php artisan test
